apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
        - name: cloud-api-adaptor-con
          env:
            - name: STACKIT_SERVICE_ACCOUNT_KEY_PATH
              value: /root/.stackit/credentials.json
          volumeMounts:
            - mountPath: /root/.stackit
              name: creds
      volumes:
        - name: creds
          secret:
            secretName: peer-pods-secret
