apiVersion: v1
kind: Secret
metadata:
  annotations:
    serviceaccount.resources.gardener.cloud/name: csi-wrapper
    serviceaccount.resources.gardener.cloud/namespace: kube-system
  labels:
    resources.gardener.cloud/class: shoot
    resources.gardener.cloud/purpose: token-requestor
  name: shoot-access-csi-wrapper
type: Opaque
